default_stages:
- pre-commit
repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.9.1
- hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
  - id: requirements-txt-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - args:
    - --autofix
    - --indent
    - '2'
    id: pretty-format-yaml
  repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
- hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
- hooks:
  - args:
    - --install-types
    - --non-interactive
    - --ignore-missing-import
    files: circlify.py
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.1
- hooks:
  - id: tests
    entry: python -m unittest
    language: system
    name: tests
    pass_filenames: false
  repo: local
- hooks:
  - id: remark
    args: [--output, --frail]     # list of args for remark
    additional_dependencies: [remark-cli@8.0.1, remark-preset-lint-recommended@4.0.1]
  repo: https://github.com/MaratFM/pre-commit-remark
  rev: 1.0.0
