default_stages:
- commit
repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.28.0
- hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
  - id: requirements-txt-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - args:
    - --autofix
    - --indent
    - '2'
    id: pretty-format-yaml
  repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
- hooks:
  - id: black
    language_version: python3
  repo: https://github.com/python/black
  rev: 22.6.0
- hooks:
  - additional_dependencies:
    - flake8-comprehensions>=3.1.0
    id: flake8
    language: python_venv
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
- hooks:
  - args:
    - --install-types
    - --non-interactive
    - --ignore-missing-import
    files: circlify.py
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
- hooks:
  - id: tests
    entry: python -m unittest
    language: system
    name: tests
    pass_filenames: false
  repo: local
