# This workflow will install Python dependencies, run tests coverage

name: Coverage report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python latest
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r test-requirements.txt
    - name: Generate coverage report
      run: |
        python -m coverage erase
        python -m coverage run --source=circlify tests.py
        python -m coverage xml

    # upload to codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true


